version: "3.9"

services:
  ecs:
    build:
      dockerfile: Dockerfile
    entrypoint: ./scripts/ecs.sh

  kvs-main:
    build:
      dockerfile: Dockerfile
    links:
      - ecs:ecs
    depends_on:
      - ec
    command:
      - "5311"
    entrypoint: ./scripts/kvs.sh

  kvs:
    build:
      dockerfile: Dockerfile
    links:
      - ecs:ecs
    depends_on:
      - ecs
    entrypoint: ./scripts/kvs.sh

  client:
    build:
      dockerfile: Dockerfile
    links:
      - kvs-main:kvs-main
    depends_on:
      - kvs-main
    stdin_open: true
    tty: true
    entrypoint: ./scripts/client.sh


  #performance-test1:
  #  build:
  #    dockerfile: Dockerfile
  #  links:
  #    - kvs-main:kvs-main
  #  depends_on:
  #    - kvs-main
  #  entrypoint: ./scripts/performance-test-1.sh
