version: "3.9"
services:
  ecs:
    build:
      context: ../
      dockerfile: ./docker/ecs/Dockerfile
  kvs-main:
    build:
      context: ../
      dockerfile: ./docker/kvs/Dockerfile
    links:
      - ecs:ecs
    depends_on:
      - ec
    command:
      - "5311"
  kvs:
    build:
      context: ../
      dockerfile: ./docker/kvs/Dockerfile
    links:
      - ecs:ecs
    depends_on:
      - ecs
  client:
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
    links:
      - kvs-main:kvs-main
    depends_on:
      - kvs-main
    stdin_open: true
    tty: true